### ISSUE TITLE
关于与 BID 在TaskII.A 的对比实验的询问

### ISSUE THREAD

**Issue by Sh3lock** [gy65896/OneRestore#1]
嗨，首先祝贺你们做出如此优秀的工作！也很感激你们的开源！在阅读完你们精彩的论文之后，我心中产生了一个疑问渴望得到你们的解答。
我注意到，BID（ECCV 2022）在Task II.A 数据集上的实验与你们的论文方向十分匹配，请问一下你们有在 Task II.A 数据集上做过相关的实验吗？

**Comment by gy65896** [comment]
Thank you for your attention!

I haven’t conducted the experiment on this dataset yet. If I have time, I will perform this test and compare our method with BID.
