### ISSUE TITLE
Dataset (CDD-11) unavailable

### ISSUE THREAD

**Issue by b-bad** [gy65896/OneRestore#10]
The dataset linked in the README is now not available, could you please update it? Thank you very much.

**Comment by gy65896** [comment]
I have attempted to download it without my onedrive account, but this link is still available.

**Comment by gy65896** [comment]
Is this link https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2YvcyFBczNyQ0RST25yYkxncXBlekc0c2FvLXU5ZGREaHc%5FZT1BMFJFSHg&id=CBB69E4E3408EBCD%2138238&cid=CBB69E4E3408EBCD ?

**Comment by b-bad** [comment]
I'm sorry, but I can't open this link either. It says “The request is blocked”. I also asked my friend to try to open this link but he failed too.

**Comment by b-bad** [comment]
Issue solved. The way to do this is to change the mode of the VPN from rule to global.
