### ISSUE TITLE
about continue training？

### ISSUE THREAD

**Issue by ScarletBlaze** [gy65896/OneRestore#12]
Thank you for sharing your excellent work. 

I have a question for you. When the server unexpectedly interrupts the training program, how can I set it up so that the model can inherit the previous parameters and state to continue training? Should I set the "--restore-model-path" parameter (for restore models) or the "--embedder-model-path" parameter (for embedder models)? How should I set it up? 
Looking forward to your reply

**Comment by gy65896** [comment]
You can set `restore-model-path` to load trained model
