### ISSUE TITLE
Code for how to synthesize low-quality image

### ISSUE THREAD

**Issue by mrluin** [gy65896/OneRestore#2]
Hello, thanks for your work.

Could you please provide code for how to synthesize low-quality images?

**Comment by gy65896** [comment]
Thank you for your attention! 

I will organize the code of the dataset synthesis part. This will be released soon.

**Comment by mrluin** [comment]
@gy65896 Thanks, I'm interested in how to synthesize snow masks in Python without using PhotoShop.

**Comment by gy65896** [comment]
For this issue, we introduce the snow masks from the snow100k dataset which has 50,000 snow masks, so I think it's enough, and then we generate snowy images by formula. You can open this link for more details: https://sites.google.com/view/yunfuliu/desnownet.

**Comment by mrluin** [comment]
Thanks for your reply.

**Comment by gy65896** [comment]
The code for data synthesis has been released.
