### ISSUE TITLE
The Results of Your methods on the PromptIR multi-in-one setting 

### ISSUE THREAD

**Issue by Amazingren** [gy65896/OneRestore#3]
Dear @gy65896 

It's really nice work and thanks for making the dataset and code public!

I am curious if you have tested your method on another all-in-one IR setting, i.e., the Prompt/AirNet setting.

If you have tried the experiments, may I know the performance?

Best regards and many thanks,

**Comment by gy65896** [comment]
Dear Ren,

Thank you for your attention!

This experiment is not included in my work. I will do it if I have time.

Best Regards,
Yu Guo

**Comment by Amazingren** [comment]
> Dear Ren,
> 
> Thank you for your attention!
> 
> This experiment is not included in my work. I will do it if I have time.
> 
> Best Regards, Yu Guo

Got it, thanks for the quick response! :) 

Bests,
