### ISSUE TITLE
How to train with multi GPUs?

### ISSUE THREAD

**Issue by Amazingren** [gy65896/OneRestore#4]
Hi @gy65896 

Thanks for your nice work.

I am trying to reproduce your method from scratch. 

However, when I train the proposed method (i.e., embedded) with 4 GPUs, there is always only one GPU is used though I already used 'CUAD_VISIBLE_DEVICES=0,1,2,3'

It would be super helpful to hear some suggestions from you.

Best regards and many thanks,

**Comment by gy65896** [comment]
Dear Ren,

My model was originally trained on multi-GPU, but I have not released the code for distributed training. Thank you for your suggestion. I will update it and inform you in a couple of days.

Best Regards,
Yu Guo

**Comment by Amazingren** [comment]
> Dear Ren,
> 
> My model was originally trained on multi-GPU, but I have not released the code for distributed training. Thank you for your suggestion. I will update it and inform you in a couple of days.
> 
> Best Regards, Yu Guo

Nice! I'm waiting for it! 👍  : )
With warm regards,

**Comment by gy65896** [comment]
Hi Ren,

The code for multiple training is released. You can try it. I tested it and there is no problem. If you encounter any problems, we can communicate again.

Yu Guo

**Comment by Amazingren** [comment]
> Hi Ren,
> 
> The code for multiple training is released. You can try it. I tested it and there is no problem. If you encounter any problems, we can communicate again.
> 
> Yu Guo

Good, thanks for the quick action! 👍 

Bests,
