### ISSUE TITLE
The GPUs for training Text/Visual Embedder

### ISSUE THREAD

**Issue by Cyyyyyb** [gy65896/OneRestore#5]
Hi @gy65896 

Thanks for your nice work.

I am trying to reproduce your method from scratch.

I would like to know what GPU the text/visual embedder is trained on.

Best regards and many thanks,

**Comment by gy65896** [comment]
Thanks for your attention!

Due to the small GPU memory consumption compared with the restoration model, we just used a single 3090 GPU to train text and visual embedded.

**Comment by Cyyyyyb** [comment]
> Thanks for your attention!
> 
> Due to the small GPU memory consumption compared with the restoration model, we just used a single 3090 GPU to train text and visual embedded.

Got it, thanks for the quick response!

However, when I used a single 3090 GPU to train text and visual embedded, I reported an error and would like to ask you for help.

Best regards and many thanks,

I use this line command to run the code: python train_Embedder.py 
--train-dir ./data/CDD-11_train --test-dir ./data/CDD-11_test --check-dir ./ckpts --batch 256  --num-workers 0 --epoch 200 --lr 1e-4 --lr-decay 50
<img width="523" alt="Snipaste_2024-08-05_20-32-11" src="https://github.com/user-attachments/assets/551a3bdf-e914-4877-8a4c-077145ef2a5f">

**Comment by gy65896** [comment]
Have you attempted to set batch_size as 128? Perhaps I use this set of parameters on another device.

**Comment by Zhong-Polyu** [comment]
> > Thanks for your attention!
> > Due to the small GPU memory consumption compared with the restoration model, we just used a single 3090 GPU to train text and visual embedded.
> 
> Got it, thanks for the quick response!
> 
> However, when I used a single 3090 GPU to train text and visual embedded, I reported an error and would like to ask you for help.
> 
> Best regards and many thanks,
> 
> I use this line command to run the code: python train_Embedder.py --train-dir ./data/CDD-11_train --test-dir ./data/CDD-11_test --check-dir ./ckpts --batch 256 --num-workers 0 --epoch 200 --lr 1e-4 --lr-decay 50 <img alt="Snipaste_2024-08-05_20-32-11" width="523" src="https://private-user-images.githubusercontent.com/154773240/355102177-551a3bdf-e914-4877-8a4c-077145ef2a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDgzMTksIm5iZiI6MTcyNDc0ODAxOSwicGF0aCI6Ii8xNTQ3NzMyNDAvMzU1MTAyMTc3LTU1MWEzYmRmLWU5MTQtNDg3Ny04YTRjLTA3NzE0NWVmMmE1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwODQwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTdlMmE5N2ZmYTRlMDczNGVmYjJhMDE1NWE0MzQ1NTQ2M2QzMWQwMTg0NzQ1NzU3YmM0NWU1ZThkODZiNjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X_OSPrEKIx14-jjYYIDi8A9RYbK-2oauAGuFmv12kAw">



Hi, I encountered the same problem. I found it caused by the memory cost at the validation stage.
Add the ''with torch.no_grad():'' after model.val(), solved!

**Comment by gy65896** [comment]
Sorry, I can't open your picture. Could you re-upload this picture or describe this error?

**Comment by gy65896** [comment]
Thank you for your mention. I will update the code.
