### ISSUE TITLE
Code for Low-quality Images Generation

### ISSUE THREAD

**Issue by Zhong-Polyu** [gy65896/OneRestore#6]
Hi Dr Guo, thanks for the open source of this great work. 

I wonder if the code for low-quality dataset could be released?  This would be a great help for my current project research. Appreciate if this could be responded.

Thank you!

**Comment by gy65896** [comment]
OK, I will update the part of these codes as soon as possible.

**Comment by Cyyyyyb** [comment]
> OK, I will update the part of these codes as soon as possible.
您好，如果您能提供生成低质量图像特别是混合退化的数据集的代码，这将对我非常有帮助，谢谢！

**Comment by gy65896** [comment]
Thank you for your attention. The code for data synthesis has been released.

**Comment by Zhong-Polyu** [comment]
> Thank you for your attention. The code for data synthesis has been released.

Thanks for the update!
