### ISSUE TITLE
About Results in Table 2

### ISSUE THREAD

**Issue by Aitical** [gy65896/OneRestore#7]
This is excellent work, providing a new research benchmark with an open-source implementation that allows us to quickly follow up on the research.

In Table 2, several models such as MPRNet, PromptIR, and AirNet were trained and compared using the COD-11 dataset introduced in this paper. To facilitate rapid verification and comparison, *we kindly request the open-sourcing of the checkpoints for these benchmark models listed in Table 2*.

We appreciate the significant contribution this work has made to the field and believe that sharing these model checkpoints would further enhance its impact and accelerate progress in this area of research.

Thank you for considering this request.

**Comment by gy65896** [comment]
Thank you for your question. Some of the trained checkpoints may not be directly compatible with the original model. If needed, I can work on organizing this part later, but it may be time-consuming.

**Comment by Aitical** [comment]
## Request for Sharing Pre-Trained Weights for Benchmark Models in Table 2

Thank you for your excellent work and significant contributions to the field. I found the comparison of models in Table 2, particularly on the COD-11 dataset, extremely valuable for further research and analysis.

To accelerate replication and facilitate detailed model and feature analysis—especially for studying composite degradation characteristics—**_I kindly request that you share the pre-trained weights for the benchmark models_** listed in Table 2. If providing the weights for all models is too time-consuming, sharing representative models such as NAFNet, Restormer, and PromptIR would be greatly appreciated.

Open-sourcing these pre-trained weights would not only enhance reproducibility but also significantly benefit the research community by enabling more in-depth comparisons and analysis.

Thank you for considering this request.
