### ISSUE TITLE
Release of supplementary materials.

### ISSUE THREAD

**Issue by jin-cao-tma** [gy65896/OneRestore#8]
Dear author,
   Since lots of results are in supplementary materials, would you please release them to help us follow your work?

**Comment by gy65896** [comment]
You can use the released ckpts to generate the results in my supplementary materials.

**Comment by jin-cao-tma** [comment]
> You can use the released ckpts to generate the results in my supplementary materials.

Thanks for the reply. In fact, we want the detailed performances of these compared methods, which is important for the following works. Would you release them?
![image](https://github.com/user-attachments/assets/34fd51a3-36b5-47dc-a21d-e0ae409157e5)

**Comment by gy65896** [comment]
I can release the image results, however, the ckpts of these methods need to be organized further.

**Comment by jin-cao-tma** [comment]
> I can release the image results, however, the ckpts of these methods need to be organized further.

Thanks! That's enough. It will be better if you can also release the PSNR and SSIM of all the compared methods in different degradation settings.
![image](https://github.com/user-attachments/assets/5b8575a4-5634-4bde-b34d-9d4acf30a431)

**Comment by gy65896** [comment]
OK, I will check and update this part, which may be accomplished in a couple of days.

**Comment by jin-cao-tma** [comment]
> OK, I will check and update this part, which may be accomplished in a couple of days.

Thanks. Looking forward to it.

**Comment by gy65896** [comment]
We have updated part of the numerical and visual results, the other two methods will be released soon.

**Comment by jin-cao-tma** [comment]
> We have updated part of the numerical and visual results, the other two methods will be released soon.

Thanks a lot.
