### ISSUE TITLE
Release artifacts (models, datasets) on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [gy65896/OneRestore#9]
Hi @gy65896,

Niels here from the open-source team at Hugging Face. I discovered your work through ECCV, I indexed your paper: https://huggingface.co/papers/2407.04621. Congrats on getting it accepted! I work together with [AK](https://x.com/_akhaliq) on improving the visibility of researchers' work on the hub.

It'd be great to make the checkpoints and data available on the 🤗 hub, rather than Github, to improve their discoverability/visibility. We can add tags so that people find them when filtering https://huggingface.co/models.

We can then add tags such as "image-to-image" so that people find them at https://huggingface.co/models?pipeline_tag=image-to-image&sort=trending.

## Uploading models

See here for a guide: https://huggingface.co/docs/hub/models-uploading. 

In this case, we could leverage the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds `from_pretrained` and `push_to_hub` to any custom `nn.Module`. Alternatively, one can leverages the [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file) one-liner to download a checkpoint from the hub. 

We encourage researchers to push each model checkpoint to a separate model repository, so that things like download stats also work. We can then also link the checkpoints to the paper page.

## Uploading dataset

Would be awesome to make the training dataset available on 🤗 , so that people can do:

```python
from datasets import load_dataset

dataset = load_dataset("your-hf-org/your-dataset")
```
See here for a guide: https://huggingface.co/docs/datasets/image_dataset

Besides that, there's the [dataset viewer](https://huggingface.co/docs/hub/en/datasets-viewer) which allows people to quickly explore the first few rows of the data in the browser.

Let me know if you're interested/need any help regarding this!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by NielsRogge** [comment]
Hi @gy65896, any reason to close this PR?

**Comment by gy65896** [comment]
Thank you for your suggestion. Indeed, I have uplaoded my code in hugging face and I will consider to upload my dataset to this platform.

**Comment by gy65896** [comment]
> Hi @gy65896, any reason to close this PR?

Hi @NielsRogge, our [demo](https://huggingface.co/spaces/gy65896/OneRestore), [code](https://huggingface.co/gy65896/OneRestore), [checkpoints](https://huggingface.co/gy65896/OneRestore/tree/main/ckpts), and [datasets](https://huggingface.co/datasets/gy65896/CDD-11) are released on hugging face. Thanks for your suggestions.

**Comment by NielsRogge** [comment]
Congrats, that's amazing!

Some notes:
* opened a PR to link the demo to the paper: https://huggingface.co/spaces/gy65896/OneRestore/discussions/1
* opened a PR to link the datasets to the paper: https://huggingface.co/datasets/gy65896/CDD-11/discussions/1
* it would be cool to remove checkpoints from the Space, and instead leverage [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file) to load them. This way, the models + space automatically get linked.

This method could also be used inside this Github repo to download checkpoints :)

**Comment by NielsRogge** [comment]
I've opened https://github.com/gy65896/OneRestore/pull/14 as I've got a suggestion for improvement :)
